logger: true
arch: "bayes_rfnet"
depth: 16
s: 0.0001
workers: 4
multi-gpu: false
batch-size: 256
test-batch-size: 256
admm-epochs: 1
optmzr: "adam"
lr: 0.0001
lr-decay: 30
momentum: 0.9
weight-decay: 0.0001
no-cuda: false
seed: 1
log-interval: 159
save-model: ""
masked-retrain: true
verbose: false
admm: false
rho: 0.0001
rho-num: 4
sparsity-type: "irregular"
combine-progressive: false
lr-scheduler: "default"
warmup: false
warmup-lr: 0.0001
warmup-epochs: 0
mixup: false
alpha: 0.0
smooth: false
smooth-eps: 0.0
no-tricks: false
dataset: "dronerc"
task-folder: "tasks-1024sl"
exp-name: "exp-drc-bresenet-2"
base-path: ""
save-path: ""
input-size: 1024 # 16382
classes: 15
tasks: 3
disjoint_classifier: false
mask: ""
config-file: ""
config-setting: "1"
config-shrink: 0.35
heritage-weight: false ###
adaptive-mask: false
admm-mask: false
adaptive-ratio: 0.9
epochs: 2
epochs-prune: 2
epochs-mask-retrain: 2
mask-admm-epochs: 1
load-model: "" # "dronerc/exp-drc-1024sl-3-p20-3t-batchnorm-KLloss-testnan3/task0/rfnet16.pt" 
load-model-pruned: "" #"dronerc/exp-drc-1024sl-redo-bns-2/task1/prunned_rfnet16_0.1__adam_irregular.pt"